name = "InvariantMeasures"
uuid = "07926553-d30c-41c2-8456-6c4d18765e90"
authors = ["Isaia Nisoli <nisoli@im.ufrj.br>, Federico Poloni <federico.poloni@unipi.it> and contributors"]
version = "0.1.2"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
CRlibm = "96374032-68de-5a5b-8d9e-752f78720389"
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastRounding = "fa42c844-2597-5d31-933b-ebd51ab2693f"
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalOptimisation = "c7c68f13-a4a2-5b9a-b424-07d005f8d9d2"
IntervalRootFinding = "d2bf35a9-74e0-55ec-b149-d360ff49b807"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TaylorModels = "314ce334-5f6e-57ae-acf6-00b6e903104a"
TaylorSeries = "6aa5eb33-94cf-58f4-a9d0-e4b2c4fc25ea"
ValidatedNumerics = "d621b6e3-7715-5857-9c6f-c67000ef6083"

[compat]
AbstractFFTs = "0.8.0, 1"
Arpack = "0.4.0, 0.5"
DualNumbers = "0.6.4"
FFTW = "1"
FastRounding = "0.2.0, 0.3"
FastTransforms = "0.14"
Glob = "1"
IntervalArithmetic = "0.17.7, 0.20"
IntervalOptimisation = "0.4.2"
IntervalRootFinding = "0.5"
LaTeXStrings = "1.2.1"
ProgressMeter = "1"
RecipesBase = "1.1.1"
Revise = "3"
StaticArrays = "1"
StatsPlots = "0.14.34"
SymbolicUtils = "0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19"
Symbolics = "3, 4"
TaylorModels = "0.4, 0.5, 0.6"
TaylorSeries = "0.10.11, 0.11, 0.12"
ValidatedNumerics = "0.11, 0.12"
julia = "1.5, 1.6, 1.7, 1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
